Document: konstruktor
Title: Debian konstruktor Manual
Author: <insert document author here>
Abstract: This manual describes what konstruktor is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/konstruktor/konstruktor.sgml.gz

Format: postscript
Files: /usr/share/doc/konstruktor/konstruktor.ps.gz

Format: text
Files: /usr/share/doc/konstruktor/konstruktor.text.gz

Format: HTML
Index: /usr/share/doc/konstruktor/html/index.html
Files: /usr/share/doc/konstruktor/html/*.html
